import type { Metadata } from 'next';

import { AtlasNav, AtlasShell, ConceptCard, SYNTHETIC_ATLAS_PATH } from '@/components/SyntheticAtlas';
import { SI_PUBLIC_CONCEPTS, SI_PUBLIC_META } from '@/lib/atlas/synthetic-intelligence';

const SITE_URL = 'https://research.mahastrategies.com';
const URL = `${SITE_URL}${SYNTHETIC_ATLAS_PATH}/concepts`;
export const metadata: Metadata = { title: `Concept Library | ${SI_PUBLIC_META.title}`, description: 'Defined concepts used by the Synthetic Intelligence Atlas, each linked to its public evidence record.', alternates: { canonical: `${SYNTHETIC_ATLAS_PATH}/concepts` }, robots: { index: true, follow: true }, openGraph: { type: 'website', url: URL, title: `Concept Library | ${SI_PUBLIC_META.title}`, description: 'Definitions, boundaries, related concepts, and linked source records.' } };
export default function SyntheticConceptLibraryPage() { const ld = { '@context': 'https://schema.org', '@type': 'DefinedTermSet', '@id': `${URL}#terms`, name: `${SI_PUBLIC_META.title} concept library`, url: URL, hasDefinedTerm: SI_PUBLIC_CONCEPTS.map((concept) => ({ '@type': 'DefinedTerm', name: concept.label, description: concept.definition, url: `${URL}/${concept.id}` })) }; return <AtlasShell><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} /><div className="mx-auto max-w-5xl"><AtlasNav back={{ href: SYNTHETIC_ATLAS_PATH, label: SI_PUBLIC_META.shortTitle }} /><header className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Atlas library · {SI_PUBLIC_CONCEPTS.length} records</p><h1 className="mt-4 text-3xl font-light text-white md:text-5xl">Concepts with boundaries.</h1><p className="mt-6 text-sm leading-relaxed text-zinc-400">Each term is defined for this Atlas, linked to its source set, and—where necessary—paired with an explicit statement of what it does not establish.</p></header><section className="mt-12 grid gap-4 md:grid-cols-2">{SI_PUBLIC_CONCEPTS.map((concept) => <ConceptCard key={concept.id} concept={concept} />)}</section></div></AtlasShell>; }
