/** Source layer for the Quantum Computing Atlas. Evidence cutoff: 2026-07-28. */
export const QC_ATLAS_PATH = '/atlas/quantum-computing';
export const QC_REVIEW_DATE = '2026-07-28';

export type QcStatus = 'established' | 'active-research';
export const QC_STATUSES = [
  { id: 'established' as const, label: 'Established result', definition: 'A published result, standard construction, or authoritative definition. The label does not imply that every practical implementation challenge is solved.' },
  { id: 'active-research' as const, label: 'Active research', definition: 'An important open engineering or scientific question with no field-wide resolution.' },
];
export const getQcStatus = (id: QcStatus) => QC_STATUSES.find((status) => status.id === id)!;

export type QcSource = { id: string; title: string; authors: string; year: number; identifier: string; url: string; sourceType: 'primary-paper' | 'authoritative-report'; verifiedOn: string; whyHere: string };
export const QC_SOURCES: QcSource[] = [
  { id: 'nasa-qis', title: 'Quantum Information Science', authors: 'NASA', year: 2025, identifier: 'NASA QIS overview', url: 'https://www.nasa.gov/quantum-information-science/', sourceType: 'authoritative-report', verifiedOn: QC_REVIEW_DATE, whyHere: 'Authoritative public orientation on quantum information science and its research context.' },
  { id: 'shor-1995', title: 'Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer', authors: 'Peter W. Shor', year: 1995, identifier: 'arXiv:quant-ph/9508027', url: 'https://arxiv.org/abs/quant-ph/9508027', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Primary source for the factoring and discrete-logarithm algorithm.' },
  { id: 'grover-1996', title: 'A Fast Quantum Mechanical Algorithm for Database Search', authors: 'Lov K. Grover', year: 1996, identifier: 'arXiv:quant-ph/9605043', url: 'https://arxiv.org/abs/quant-ph/9605043', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Primary source for amplitude-amplification search.' },
  { id: 'feynman-1982', title: 'Simulating physics with computers', authors: 'Richard P. Feynman', year: 1982, identifier: 'DOI:10.1007/BF02650179', url: 'https://doi.org/10.1007/BF02650179', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Foundational source for quantum simulation as a motivation for quantum computation.' },
  { id: 'preskill-2018', title: 'Quantum Computing in the NISQ era and beyond', authors: 'John Preskill', year: 2018, identifier: 'arXiv:1801.00862', url: 'https://arxiv.org/abs/1801.00862', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Defines the NISQ framing and its limitations.' },
  { id: 'fowler-2012', title: 'Surface codes: Towards practical large-scale quantum computation', authors: 'Austin G. Fowler et al.', year: 2012, identifier: 'arXiv:1208.0928', url: 'https://arxiv.org/abs/1208.0928', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Primary technical overview of surface-code fault tolerance.' },
  { id: 'google-qec-2025', title: 'Quantum error correction below the surface code threshold', authors: 'Google Quantum AI and collaborators', year: 2025, identifier: 'DOI:10.1038/s41586-024-08449-y', url: 'https://doi.org/10.1038/s41586-024-08449-y', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Experimental report of below-threshold surface-code memories; it does not demonstrate a general-purpose fault-tolerant computer.' },
  { id: 'arute-2019', title: 'Quantum supremacy using a programmable superconducting processor', authors: 'Frank Arute et al.', year: 2019, identifier: 'DOI:10.1038/s41586-019-1666-5', url: 'https://doi.org/10.1038/s41586-019-1666-5', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Experimental demonstration of random-circuit sampling on a superconducting processor.' },
  { id: 'bruzewicz-2019', title: 'Trapped-ion quantum computing: Progress and challenges', authors: 'Colin D. Bruzewicz et al.', year: 2019, identifier: 'DOI:10.1007/s11128-019-2175-2', url: 'https://doi.org/10.1007/s11128-019-2175-2', sourceType: 'primary-paper', verifiedOn: QC_REVIEW_DATE, whyHere: 'Peer-reviewed review of trapped-ion hardware and its challenges.' },
  { id: 'doe-roadmap-2024', title: 'Quantum Information Science and Technology Roadmap', authors: 'U.S. Department of Energy', year: 2024, identifier: 'DOE QIS roadmap', url: 'https://www.quantum.gov/wp-content/uploads/2024/12/DOE_QIS_Roadmap_Final.pdf', sourceType: 'authoritative-report', verifiedOn: QC_REVIEW_DATE, whyHere: 'Authoritative systems-level account of hardware, algorithms, error correction, and applications.' },
];

export type QcConcept = { id: string; label: string; definition: string; whyItMatters: string; notEstablished?: string; sources: string[]; related: string[] };
export const QC_CONCEPTS: QcConcept[] = [
  { id: 'qubit', label: 'Qubit', definition: 'A controllable two-level quantum system used to represent quantum information.', whyItMatters: 'Qubits are the physical and logical units on which quantum circuits operate.', notEstablished: 'A qubit count alone does not measure computational usefulness or error-corrected capacity.', sources: ['nasa-qis', 'doe-roadmap-2024'], related: ['quantum-circuit', 'hardware-modality'] },
  { id: 'quantum-circuit', label: 'Quantum circuit', definition: 'An ordered sequence of operations and measurements acting on qubits.', whyItMatters: 'Algorithms are expressed as circuits and must be compiled to a particular device.', sources: ['nasa-qis', 'shor-1995'], related: ['qubit', 'algorithm'] },
  { id: 'hardware-modality', label: 'Hardware modality', definition: 'A physical platform used to create, control, couple, and measure qubits, such as superconducting circuits or trapped ions.', whyItMatters: 'Platform trade-offs shape connectivity, gate speed, control systems, and error mechanisms.', notEstablished: 'No single modality is established as the universal winner for fault-tolerant quantum computing.', sources: ['bruzewicz-2019', 'doe-roadmap-2024'], related: ['qubit', 'noise'] },
  { id: 'noise', label: 'Noise and decoherence', definition: 'Unwanted interactions, control imperfections, and measurement errors that alter quantum information.', whyItMatters: 'Noise limits circuit depth and makes reliable computation an engineering and theory problem.', sources: ['preskill-2018', 'fowler-2012'], related: ['hardware-modality', 'error-correction'] },
  { id: 'error-correction', label: 'Quantum error correction', definition: 'Encoding and repeated measurement methods that protect logical quantum information using multiple physical qubits.', whyItMatters: 'Large-scale algorithms require logical operations with error rates far below those of bare physical components.', notEstablished: 'A below-threshold memory experiment is not equivalent to demonstrated universal fault-tolerant computation.', sources: ['fowler-2012', 'google-qec-2025'], related: ['surface-code', 'fault-tolerance'] },
  { id: 'surface-code', label: 'Surface code', definition: 'A family of topological quantum error-correcting codes commonly studied for two-dimensional local hardware.', whyItMatters: 'It gives a concrete route from noisy physical qubits to logical qubits and gates.', sources: ['fowler-2012', 'google-qec-2025'], related: ['error-correction', 'fault-tolerance'] },
  { id: 'fault-tolerance', label: 'Fault tolerance', definition: 'A computing architecture in which errors are detected and managed so that larger computations can be performed reliably.', whyItMatters: 'It distinguishes proof-of-principle devices from systems capable of long, reliable algorithms.', sources: ['fowler-2012', 'doe-roadmap-2024'], related: ['error-correction', 'resource-estimation'] },
  { id: 'algorithm', label: 'Quantum algorithm', definition: 'A procedure designed for a quantum computer, with a specified input, circuit, measurement, and classical post-processing.', whyItMatters: 'A claimed quantum advantage is meaningful only relative to a problem, algorithm, resource model, and classical comparison.', sources: ['shor-1995', 'grover-1996'], related: ['quantum-circuit', 'resource-estimation'] },
  { id: 'quantum-simulation', label: 'Quantum simulation', definition: 'Using a controllable quantum system to model another quantum system or its dynamics.', whyItMatters: 'It is a core scientific motivation for quantum computation, especially for chemistry and materials.', sources: ['feynman-1982', 'doe-roadmap-2024'], related: ['algorithm', 'near-term-applications'] },
  { id: 'nisq', label: 'NISQ', definition: 'The noisy intermediate-scale quantum regime: devices with enough qubits for nontrivial experiments but without full fault tolerance.', whyItMatters: 'It sets realistic expectations for present-day hardware and shallow or error-mitigated experiments.', notEstablished: 'NISQ is not a guarantee of practical advantage for a particular use case.', sources: ['preskill-2018'], related: ['noise', 'near-term-applications'] },
  { id: 'resource-estimation', label: 'Resource estimation', definition: 'Estimating physical and logical qubits, gates, runtime, and classical support required for a specified algorithm and error model.', whyItMatters: 'It connects algorithmic asymptotics to plausible hardware requirements.', sources: ['fowler-2012', 'doe-roadmap-2024'], related: ['fault-tolerance', 'algorithm'] },
  { id: 'near-term-applications', label: 'Near-term applications', definition: 'Candidate uses of non-fault-tolerant or early error-corrected quantum devices, evaluated against classical baselines.', whyItMatters: 'It keeps application discussion tied to evidence and comparative performance rather than broad promises.', notEstablished: 'No general-purpose, across-domain quantum commercial advantage follows from current demonstrations.', sources: ['preskill-2018', 'doe-roadmap-2024'], related: ['nisq', 'quantum-simulation'] },
];

export type QcClaim = { id: string; slug: string; status: QcStatus; claim: string; explanation: string; limitations: string; conceptIds: string[]; sourceIds: string[]; reviewDate: string };
export const QC_CLAIMS: QcClaim[] = [
  { id: 'qc-001', slug: 'qubits-are-not-classical-bits', status: 'established', claim: 'A qubit is a quantum information carrier whose state can be prepared, transformed, and measured; it is not simply a classical bit with two labels.', explanation: 'Quantum states can be put into superpositions and correlated through entangling operations, but measurement yields classical outcomes.', limitations: 'This statement does not imply that every quantum task is faster than a classical one.', conceptIds: ['qubit', 'quantum-circuit'], sourceIds: ['nasa-qis'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-002', slug: 'hardware-platforms-have-different-tradeoffs', status: 'established', claim: 'Superconducting circuits, trapped ions, neutral atoms, photonics, and semiconductor spins are distinct hardware approaches with different engineering trade-offs.', explanation: 'They differ in how qubits are made, controlled, connected, and measured, so raw qubit counts alone are not comparable performance measures.', limitations: 'This Atlas does not rank platforms or treat the list as exhaustive.', conceptIds: ['hardware-modality', 'qubit'], sourceIds: ['bruzewicz-2019', 'doe-roadmap-2024'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-003', slug: 'noise-limits-unprotected-circuits', status: 'established', claim: 'Noise and imperfect operations limit the depth and reliability of computations performed directly on physical qubits.', explanation: 'Errors accumulate as circuits execute, which is why device performance requires more context than a qubit count.', limitations: 'Error behaviour is hardware-, operation-, and workload-dependent; this is not a single universal error-rate claim.', conceptIds: ['noise', 'nisq'], sourceIds: ['preskill-2018'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-004', slug: 'qec-encodes-logical-information', status: 'established', claim: 'Quantum error correction protects logical quantum information by distributing it across multiple physical qubits and repeatedly extracting error information.', explanation: 'The goal is to make logical failure less likely than failure of the underlying components, while preserving the computation.', limitations: 'Encoding introduces substantial qubit, control, decoding, and time overhead.', conceptIds: ['error-correction', 'fault-tolerance'], sourceIds: ['fowler-2012', 'google-qec-2025'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-005', slug: 'below-threshold-is-a-milestone-not-the-endpoint', status: 'established', claim: 'Below-threshold surface-code memory performance has been experimentally reported, but it is not yet a demonstration of general-purpose fault-tolerant quantum computing.', explanation: 'The reported experiments show logical-memory error suppression as code distance grows under defined conditions; scalable logical computation remains further work.', limitations: 'This claim describes a particular experimental result and must not be generalized to all platforms or complete algorithms.', conceptIds: ['surface-code', 'error-correction', 'fault-tolerance'], sourceIds: ['google-qec-2025'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-006', slug: 'shor-algorithm-is-conditional-on-capable-hardware', status: 'established', claim: 'Shor’s algorithm gives polynomial-time quantum algorithms for integer factorization and discrete logarithms on a suitable quantum computer.', explanation: 'This is why large-scale fault-tolerant quantum computing matters for some public-key cryptography.', limitations: 'The algorithm does not establish that a current device can break deployed cryptographic systems, nor does it apply to all cryptography.', conceptIds: ['algorithm', 'fault-tolerance'], sourceIds: ['shor-1995'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-007', slug: 'grover-search-is-quadratic', status: 'established', claim: 'Grover’s search algorithm provides a quadratic query-speedup for unstructured search in its oracle model.', explanation: 'It is often described as reducing a search from order N queries to order square-root N queries.', limitations: 'The oracle model, data loading, error correction, and classical alternatives matter in any real application.', conceptIds: ['algorithm', 'resource-estimation'], sourceIds: ['grover-1996'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-008', slug: 'simulation-is-a-core-motivation', status: 'established', claim: 'Simulating quantum physical systems is a foundational motivation for quantum computers.', explanation: 'Quantum devices may represent some quantum dynamics more naturally than classical digital simulation.', limitations: 'A motivation is not a blanket claim of practical advantage for every chemistry or materials task.', conceptIds: ['quantum-simulation', 'near-term-applications'], sourceIds: ['feynman-1982', 'doe-roadmap-2024'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-009', slug: 'random-circuit-sampling-is-narrow', status: 'established', claim: 'Random-circuit sampling experiments demonstrate control over specific computational tasks, not a general-purpose application advantage.', explanation: 'The 2019 superconducting experiment benchmarked a prescribed sampling task against then-available classical methods.', limitations: 'Classical simulation methods and comparisons evolve; this claim does not use the experiment as evidence for broad commercial utility.', conceptIds: ['quantum-circuit', 'nisq'], sourceIds: ['arute-2019'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-010', slug: 'near-term-advantage-is-unsettled', status: 'active-research', claim: 'Whether a NISQ device delivers a durable, practically relevant advantage for a specific real-world workload remains an active research question.', explanation: 'Evidence must compare an end-to-end quantum workflow with the best relevant classical methods under stated accuracy and cost constraints.', limitations: 'This is not a claim that no near-term advantage will occur; it records an unresolved evidential and engineering question.', conceptIds: ['nisq', 'near-term-applications'], sourceIds: ['preskill-2018', 'doe-roadmap-2024'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-011', slug: 'fault-tolerant-scale-is-active-research', status: 'active-research', claim: 'The physical resources, decoding, control, and integration needed for useful large-scale fault-tolerant computation remain active engineering and research problems.', explanation: 'Surface codes supply a framework, but complete systems must coordinate many layers and achieve application-specific logical performance.', limitations: 'Resource estimates depend on target algorithms, code choices, hardware error models, and architectural assumptions.', conceptIds: ['fault-tolerance', 'resource-estimation', 'surface-code'], sourceIds: ['fowler-2012', 'doe-roadmap-2024'], reviewDate: QC_REVIEW_DATE },
  { id: 'qc-012', slug: 'applications-need-classical-comparisons', status: 'established', claim: 'Claims about quantum applications require task-specific comparisons to credible classical baselines.', explanation: 'An algorithmic speedup, a hardware demonstration, and a useful end-to-end application are different evidence categories.', limitations: 'This Atlas does not publish performance leaderboards or commercial forecasts.', conceptIds: ['near-term-applications', 'algorithm', 'resource-estimation'], sourceIds: ['preskill-2018', 'doe-roadmap-2024'], reviewDate: QC_REVIEW_DATE },
];

export const QC_META = { title: 'Quantum Computing Atlas', shortTitle: 'Quantum Computing Atlas', description: 'A source-led, machine-readable research library for quantum computing concepts, hardware, error correction, algorithms, limitations, and near-term applications.', version: '0.1.0', datePublished: QC_REVIEW_DATE, dateModified: QC_REVIEW_DATE, lastReviewed: QC_REVIEW_DATE, evidenceCutoff: QC_REVIEW_DATE, license: 'CC BY 4.0', statusBadge: 'First edition · 12 source-bounded claims' };
export const getQcClaim = (id: string) => QC_CLAIMS.find((claim) => claim.id === id);
export const getQcConcept = (id: string) => QC_CONCEPTS.find((concept) => concept.id === id);
export const getQcSource = (id: string) => QC_SOURCES.find((source) => source.id === id);
