import { SI_PUBLIC_CLAIMS, SI_PUBLIC_CONCEPTS, SI_PUBLIC_SOURCES, type SiClaim, type SiConcept, type SiSource } from '@/lib/atlas/synthetic-intelligence';

export type SiClaimTopic = { id: string; label: string; description: string; claimIds: string[] };
export const SI_CLAIM_TOPICS: SiClaimTopic[] = [
  { id: 'model-foundations', label: 'Model foundations and adaptation', description: 'Architecture, scaling, pre-training, post-training, and inference-time computation.', claimIds: ['si-001', 'si-002', 'si-003', 'si-004', 'si-005', 'si-006', 'si-007'] },
  { id: 'retrieval-tools-agents', label: 'Retrieval, tools, and agents', description: 'How retrieval and external tools change the system being evaluated.', claimIds: ['si-008', 'si-009', 'si-010'] },
  { id: 'evaluation-and-reliability', label: 'Evaluation and reliability', description: 'What benchmarks measure, how measurements drift, and why reliability changes long-horizon performance.', claimIds: ['si-011', 'si-012', 'si-013', 'si-014', 'si-015', 'si-016', 'si-017', 'si-018', 'si-019', 'si-023'] },
  { id: 'reporting-and-forecasting', label: 'Reporting and forecasting boundaries', description: 'Self-reports, forecast instability, and the boundary between a conditional scenario and a prediction.', claimIds: ['si-020', 'si-021'] },
];

export type SiComparison = { slug: string; title: string; question: string; distinction: string; decisionUse: string; contextDependence: string; claimIds: string[]; conceptIds: string[] };
export const SI_COMPARISONS: SiComparison[] = [
  { slug: 'llms-vs-agentic-systems', title: 'LLMs vs. agentic systems', question: 'What is being assessed: a model, or a system that uses a model?', distinction: 'An LLM produces outputs from its weights and supplied context. An agentic system adds a loop, tools, an environment, stopping rules, and often evaluation-specific scaffolding. Measured system performance therefore cannot be assigned to the underlying model alone.', decisionUse: 'For procurement or research comparison, specify the model, interface, tools, permissions, environment, and recovery loop—not only the model name.', contextDependence: 'The model/system boundary depends on the task. In a short text-generation task, scaffolding may be minimal; in coding or operations tasks, interface and tool design can dominate outcomes.', claimIds: ['si-009', 'si-010', 'si-011', 'si-019', 'si-023'], conceptIds: ['large-language-models', 'tool-use', 'agent-loop', 'coding-agents', 'evaluation'] },
  { slug: 'retrieval-vs-fine-tuning', title: 'Retrieval vs. fine-tuning', question: 'Should a system receive information at inference time, or have its behaviour adapted through training?', distinction: 'Retrieval-augmented generation conditions an output on documents fetched at inference time. Fine-tuning changes behaviour after pre-training. They are different interventions and can be combined; neither is a generic substitute for the other.', decisionUse: 'Choose based on evidence requirements: retrieval can make the immediate source context inspectable, while fine-tuning targets behaviour or task adaptation. Evaluate both against the same task, corpus, and update assumptions.', contextDependence: 'Retrieval quality, corpus governance, prompt construction, and the fine-tuning objective all shape outcomes. The current source set does not support a universal performance ranking.', claimIds: ['si-005', 'si-008', 'si-023'], conceptIds: ['retrieval-augmented-generation', 'post-training', 'evaluation', 'large-language-models'] },
  { slug: 'tool-use-vs-autonomous-execution', title: 'Tool use vs. autonomous execution', question: 'Does access to a tool establish autonomous task completion?', distinction: 'Tool use means a model can invoke external functions and incorporate returned results. Autonomous execution additionally requires an iterated system to select actions, handle failures, observe outcomes, and terminate appropriately across a task.', decisionUse: 'Treat tool access as one capability of a system. For higher-stakes workflows, ask for measured success, failure recovery, supervision, permissions, and rollback—not a tool-call demonstration.', contextDependence: 'Autonomy is not a binary property. The required evidence grows with task length, consequence, environmental variability, and the ability to reverse errors.', claimIds: ['si-009', 'si-010', 'si-019', 'si-023'], conceptIds: ['tool-use', 'agent-loop', 'reliability-compounding-error', 'long-horizon-task-completion'] },
  { slug: 'local-inference-vs-cloud-inference', title: 'Local inference vs. cloud inference', question: 'How does the delivery mode change what can be evaluated and governed?', distinction: 'Local inference runs on user-controlled hardware; cloud inference relies on a served endpoint. A hosted endpoint can change over time on fixed prompts, while a local deployment can make a fixed artifact and environment more reproducible.', decisionUse: 'For reproducibility, privacy, and auditability, record the deployment mode, model artifact or API version, date, configuration, and surrounding system—not just the prompt and output.', contextDependence: 'Local and cloud deployments differ in hardware, model availability, operations, security, and update mechanisms. The Atlas does not claim a current capability gap between them.', claimIds: ['si-017', 'si-020', 'si-023'], conceptIds: ['local-inference', 'evaluation', 'governance-accountability'] },
  { slug: 'benchmark-performance-vs-real-world-reliability', title: 'Benchmark performance vs. real-world reliability', question: 'What can a benchmark score establish about dependable work?', distinction: 'A benchmark score measures a system on a defined task distribution under a stated scaffolding configuration and date. Reliable real-world performance additionally depends on distribution shift, error recovery, interfaces, tool permissions, and the cost of failures.', decisionUse: 'Use benchmark results as scoped measurements. Before deployment, require task-relevant evaluation, repeated trials, error analysis, drift monitoring, and a plan for human oversight or recovery.', contextDependence: 'Transfer depends on whether the benchmark, environment, workflow, and reliability threshold match the decision at hand. A strong score is not evidence of general capability or dependable autonomy.', claimIds: ['si-011', 'si-012', 'si-013', 'si-014', 'si-015', 'si-016', 'si-017', 'si-018', 'si-019', 'si-023'], conceptIds: ['evaluation', 'construct-validity', 'benchmark-contamination', 'reliability-compounding-error', 'long-horizon-task-completion'] },
];

export const getDecisionClaim = (id: string): SiClaim | undefined => SI_PUBLIC_CLAIMS.find((claim) => claim.id === id);
export const getDecisionConcept = (id: string): SiConcept | undefined => SI_PUBLIC_CONCEPTS.find((concept) => concept.id === id);
export const getDecisionSource = (id: string): SiSource | undefined => SI_PUBLIC_SOURCES.find((source) => source.id === id);
export const getComparison = (slug: string) => SI_COMPARISONS.find((comparison) => comparison.slug === slug);
export const sourcesForClaims = (claimIds: string[]) => Array.from(new Set(claimIds.flatMap((id) => getDecisionClaim(id)?.sourceIds ?? []))).map(getDecisionSource).filter((source): source is SiSource => Boolean(source));
