import type { Metadata } from 'next';

import { AtlasNav, AtlasShell, SourceCard, SYNTHETIC_ATLAS_PATH } from '@/components/SyntheticAtlas';
import { SI_PUBLIC_META, SI_PUBLIC_SOURCES } from '@/lib/atlas/synthetic-intelligence';

const SITE_URL = 'https://research.mahastrategies.com';
const URL = `${SITE_URL}${SYNTHETIC_ATLAS_PATH}/sources`;
export const metadata: Metadata = { title: `Source Library | ${SI_PUBLIC_META.title}`, description: 'Content-verified primary papers, documentation, and research-organization publications used by the public Synthetic Intelligence Atlas.', alternates: { canonical: `${SYNTHETIC_ATLAS_PATH}/sources` }, robots: { index: true, follow: true }, openGraph: { type: 'website', url: URL, title: `Source Library | ${SI_PUBLIC_META.title}`, description: 'Content-verified evidence records, annotations, and claim links.' } };
export default function SyntheticSourceLibraryPage() { const ld = { '@context': 'https://schema.org', '@type': 'CollectionPage', '@id': `${URL}#page`, name: `${SI_PUBLIC_META.title} source library`, url: URL, hasPart: SI_PUBLIC_SOURCES.map((source) => ({ '@type': 'CreativeWork', name: source.title, url: `${URL}/${source.id}`, identifier: source.identifier })) }; return <AtlasShell><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} /><div className="mx-auto max-w-5xl"><AtlasNav back={{ href: SYNTHETIC_ATLAS_PATH, label: SI_PUBLIC_META.shortTitle }} /><header className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-widest text-cyan-300">Atlas library · {SI_PUBLIC_SOURCES.length} content-verified sources</p><h1 className="mt-4 text-3xl font-light text-white md:text-5xl">A source trail you can inspect.</h1><p className="mt-6 text-sm leading-relaxed text-zinc-400">Every public source was content-verified during this review. A source record explains its role; it does not claim that the Atlas endorses the paper’s argument or that the field agrees with it.</p></header><section className="mt-12 grid gap-4 md:grid-cols-2">{SI_PUBLIC_SOURCES.map((source) => <SourceCard key={source.id} source={source} />)}</section></div></AtlasShell>; }
