import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';

import { AtlasNav, AtlasShell, ClaimCard, SourceCard, SYNTHETIC_ATLAS_PATH } from '@/components/SyntheticAtlas';
import { SI_PUBLIC_CLAIMS, SI_PUBLIC_META, SI_PUBLIC_SOURCES, getPublicSiClaim, getSiStatus } from '@/lib/atlas/synthetic-intelligence';

const SITE_URL = 'https://research.mahastrategies.com';
export async function generateStaticParams() { return SI_PUBLIC_CLAIMS.map((claim) => ({ claimId: claim.id })); }
export async function generateMetadata({ params }: { params: Promise<{ claimId: string }> }): Promise<Metadata> { const claim = getPublicSiClaim((await params).claimId); if (!claim) return { title: 'Claim not found' }; const url = `${SITE_URL}${SYNTHETIC_ATLAS_PATH}/claims/${claim.id}`; return { title: `${claim.id} — ${getSiStatus(claim.status).label} | ${SI_PUBLIC_META.title}`, description: `${claim.claim} Status: ${getSiStatus(claim.status).label}.`, alternates: { canonical: `${SYNTHETIC_ATLAS_PATH}/claims/${claim.id}` }, robots: { index: true, follow: true }, openGraph: { type: 'article', url, title: claim.claim, description: claim.explanation } }; }
export default async function SyntheticClaimPage({ params }: { params: Promise<{ claimId: string }> }) { const claim = getPublicSiClaim((await params).claimId); if (!claim) notFound(); const sources = claim.sourceIds.map((id) => SI_PUBLIC_SOURCES.find((source) => source.id === id)).filter((source): source is NonNullable<typeof source> => Boolean(source)); const index = SI_PUBLIC_CLAIMS.findIndex((entry) => entry.id === claim.id); const previous = SI_PUBLIC_CLAIMS[index - 1]; const next = SI_PUBLIC_CLAIMS[index + 1]; const url = `${SITE_URL}${SYNTHETIC_ATLAS_PATH}/claims/${claim.id}`; const ld = { '@context': 'https://schema.org', '@type': 'Claim', '@id': `${url}#claim`, identifier: claim.id, url, text: claim.claim, description: claim.explanation, dateModified: claim.reviewDate, author: { '@type': 'Person', name: 'Mayone Maha Rajan' }, citation: sources.map((source) => ({ '@type': 'CreativeWork', name: source.title, identifier: source.identifier, url: source.url })) }; return <AtlasShell><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} /><article className="mx-auto max-w-3xl"><AtlasNav back={{ href: SYNTHETIC_ATLAS_PATH, label: SI_PUBLIC_META.shortTitle }} /><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">Claim record · edition {SI_PUBLIC_META.version}</p><ClaimCard claim={claim} statusLabel={getSiStatus(claim.status).label} detail /><section className="mt-12"><h2 className="border-b border-zinc-800 pb-3 font-mono text-[10px] uppercase tracking-widest text-zinc-500">Supporting source records · {sources.length}</h2><div className="mt-6 grid gap-4">{sources.map((source) => <SourceCard key={source.id} source={source} />)}</div></section><section className="mt-12"><h2 className="border-b border-zinc-800 pb-3 font-mono text-[10px] uppercase tracking-widest text-zinc-500">Related concepts</h2><div className="mt-5 flex flex-wrap gap-2">{claim.conceptIds.map((id) => <Link key={id} href={`${SYNTHETIC_ATLAS_PATH}/concepts/${id}`} className="border border-zinc-700 px-3 py-2 font-mono text-[10px] uppercase tracking-widest text-zinc-300 hover:border-cyan-400">{id.replaceAll('-', ' ')}</Link>)}</div></section><nav className="mt-12 flex justify-between border-t border-zinc-800 pt-6 font-mono text-[10px] uppercase tracking-widest">{previous ? <Link href={`${SYNTHETIC_ATLAS_PATH}/claims/${previous.id}`} className="text-zinc-400 hover:text-cyan-300">← {previous.id}</Link> : <span />}{next ? <Link href={`${SYNTHETIC_ATLAS_PATH}/claims/${next.id}`} className="text-zinc-400 hover:text-cyan-300">{next.id} →</Link> : null}</nav></article></AtlasShell>; }
