import Link from 'next/link';
import React from 'react';

export default function ResearchHomepage() {
  return (
    <div className="min-h-screen bg-[#0a0a0c] text-zinc-300 font-sans selection:bg-indigo-500 selection:text-white p-8 md:p-24">
      <div className="max-w-4xl w-full mx-auto">
        
        {/* TOP NAVIGATION */}
        <nav className="mb-20 flex flex-wrap items-center justify-between border-b border-zinc-800 pb-4 gap-4">
          <div className="font-mono text-[10px] tracking-widest text-zinc-500 uppercase">
            Maha Strategies <span className="text-indigo-400">///</span> Research & Architecture
          </div>
          <div className="flex gap-6">
            <Link href="/manifesto" className="font-mono text-[10px] tracking-widest text-zinc-400 hover:text-indigo-400 uppercase transition-colors">
              [ The Manifesto ]
            </Link>
            <a href="https://www.mayonemaharajan.com" target="_blank" rel="noreferrer" className="font-mono text-[10px] tracking-widest text-zinc-400 hover:text-indigo-400 uppercase transition-colors">
              [ Conceptual Architect ]
            </a>
          </div>
        </nav>

        {/* HERO / VISION */}
        <header className="mb-24">
          <div className="w-16 h-1 bg-gradient-to-r from-zinc-500 to-indigo-500 mb-8"></div>
          <h1 className="text-4xl md:text-5xl font-light tracking-wide uppercase text-white mb-6 leading-tight">
            Human-AI Collaborative <br />
            <span className="text-zinc-500">Scientific Architecture</span>
          </h1>
          <p className="text-sm md:text-base text-zinc-400 tracking-wide font-light leading-relaxed max-w-2xl border-l border-indigo-500/30 pl-4">
            An avant-garde open-access journal dedicated to exploring cross-disciplinary isomorphisms. We treat artificial intelligence not as a surrogate author, but as an advanced cognitive instrument for synthesizing complex theoretical frameworks under rigorous human curation.
          </p>
        </header>

        {/* PUBLISHED RESEARCH LIST */}
        <section>
          <div className="font-mono text-[10px] tracking-widest text-zinc-500 uppercase border-b border-zinc-800 pb-2 mb-8">
            Vol. 1 — Inaugural Synthesis
          </div>

          {/* Featured Paper Item */}
          <article className="group relative border border-zinc-800/50 bg-[#121214] p-8 hover:border-indigo-500/30 transition-all duration-300">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-6 gap-4">
              <div className="space-y-2">
                <div className="font-mono text-[10px] text-indigo-400 uppercase tracking-widest">
                  Systems Theory / Neurobiology / Astrophysics
                </div>
                <Link href="/papers/thermodynamic-isomorphism">
                  {/* Using standard sans/serif mix for academic authority */}
                  <h2 className="text-2xl text-white font-medium leading-snug group-hover:text-indigo-300 transition-colors">
                    A Unified Nonlinear Dynamical Model of Thermodynamic Runaway
                  </h2>
                </Link>
              </div>
              <div className="font-mono text-[10px] text-zinc-500 uppercase whitespace-nowrap">
                June 2026
              </div>
            </div>

            <p className="text-sm text-zinc-400 font-light leading-relaxed mb-6">
              A mathematical framework demonstrating a formal isomorphism between the runaway greenhouse effect in planetary astrophysics and the pathological collapse of the mammalian mesolimbic dopamine pathway.
            </p>

            <div className="flex flex-wrap gap-x-8 gap-y-2 pt-4 border-t border-zinc-800/50">
              <div className="flex flex-col">
                <span className="font-mono text-[9px] uppercase tracking-widest text-zinc-600 mb-1">Generated By</span>
                <span className="text-xs text-zinc-300">Antigravity, DeepMind Agentic Group</span>
              </div>
              <div className="flex flex-col">
                <span className="font-mono text-[9px] uppercase tracking-widest text-zinc-600 mb-1">Architected By</span>
                <span className="text-xs text-zinc-300">Mayone Maha Rajan</span>
              </div>
            </div>

            <Link href="/papers/thermodynamic-isomorphism" className="absolute top-8 right-8 text-zinc-500 group-hover:text-indigo-400 transition-colors">
              &#8599;
            </Link>
          </article>
        </section>

      </div>
    </div>
  );
}