import Link from 'next/link';
import type { QcClaim, QcConcept, QcSource, QcStatus } from '@/lib/atlas/quantum-computing';
export const QUANTUM_ATLAS_PATH = '/atlas/quantum-computing';
const styles: Record<QcStatus, string> = { established: 'border-emerald-400/50 bg-emerald-400/10 text-emerald-200', 'active-research': 'border-amber-400/50 bg-amber-400/10 text-amber-200' };
export function AtlasShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-[#0a0a0c] p-6 text-zinc-300 selection:bg-violet-500 selection:text-white md:p-24">{children}</main>; }
export function AtlasNav({ back }: { back?: { href: string; label: string } }) { return <nav className="mb-12 flex flex-wrap justify-between gap-4 border-b border-zinc-800 pb-4 font-mono text-[10px] uppercase tracking-widest"><Link href={back?.href ?? '/atlas'} className="text-zinc-500 hover:text-violet-300">← {back?.label ?? 'Atlas index'}</Link><span className="flex gap-5"><Link href={QUANTUM_ATLAS_PATH} className="text-zinc-400 hover:text-violet-300">Atlas</Link><Link href={`${QUANTUM_ATLAS_PATH}/concepts`} className="text-zinc-400 hover:text-violet-300">Concepts</Link><Link href={`${QUANTUM_ATLAS_PATH}/sources`} className="text-zinc-400 hover:text-violet-300">Sources</Link><Link href={`${QUANTUM_ATLAS_PATH}/methodology`} className="text-zinc-400 hover:text-violet-300">Method</Link></span></nav>; }
export function ClaimCard({ claim, label, detail = false }: { claim: QcClaim; label: string; detail?: boolean }) { return <article className={detail ? '' : 'border border-zinc-800 bg-[#121214] p-5'}><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-widest text-violet-300">{claim.id}</span><span className={`border px-2 py-1 font-mono text-[10px] uppercase tracking-widest ${styles[claim.status]}`}>{label}</span></div><h2 className="mt-4 text-base font-light leading-relaxed text-zinc-100 md:text-xl">{claim.claim}</h2><p className="mt-5 text-sm leading-relaxed text-zinc-400">{claim.explanation}</p><div className="mt-6 border-l border-amber-400/45 pl-4"><p className="font-mono text-[10px] uppercase tracking-widest text-amber-300">Limits of this claim</p><p className="mt-2 text-sm leading-relaxed text-zinc-400">{claim.limitations}</p></div>{!detail && <Link href={`${QUANTUM_ATLAS_PATH}/claims/${claim.id}`} className="mt-6 inline-block font-mono text-[10px] uppercase tracking-widest text-violet-300 hover:text-white">Read claim record →</Link>}</article>; }
export function ConceptCard({ concept }: { concept: QcConcept }) { return <article className="border border-zinc-800 bg-[#121214] p-5"><h2 className="text-lg font-light text-white">{concept.label}</h2><p className="mt-3 text-sm leading-relaxed text-zinc-400">{concept.definition}</p><Link href={`${QUANTUM_ATLAS_PATH}/concepts/${concept.id}`} className="mt-5 inline-block font-mono text-[10px] uppercase tracking-widest text-violet-300 hover:text-white">Concept record →</Link></article>; }
export function SourceCard({ source }: { source: QcSource }) { return <article className="border border-zinc-800 bg-[#121214] p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-zinc-500">{source.sourceType.replaceAll('-', ' ')} · verified</p><h2 className="mt-4 text-lg font-light text-white">{source.title}</h2><p className="mt-2 text-sm text-zinc-500">{source.authors} · {source.year}</p><p className="mt-4 text-sm leading-relaxed text-zinc-400">{source.whyHere}</p><Link href={`${QUANTUM_ATLAS_PATH}/sources/${source.id}`} className="mt-5 inline-block font-mono text-[10px] uppercase tracking-widest text-violet-300 hover:text-white">Source record →</Link></article>; }
