// Stage 5 — review.
//
// The preview is generated by running the draft through the REAL release
// serializer, not a mock of it. A preview produced by different code from the
// one that publishes is worse than no preview: it shows you something that will
// not be what ships.
//
// To do that safely the draft is parsed through publicAtlasSchema and wrapped
// in a synthetic `published` release that exists only for the duration of this
// render and is never written anywhere. That parse is the same private-field
// strip the real release performs, so what the operator sees here is exactly
// the bytes that would be served.

import { notFound } from 'next/navigation';

import { createRequestStore } from '../../_store';
import { validateAtlas } from '@/lib/atlas/builder/validate';
import { formatChangeLog } from '@/lib/atlas/builder/changelog';
import { publicAtlasSchema, releaseRecordSchema } from '@/lib/atlas/builder/schema';
import { buildAllPublicOutput, buildSitemapEntries } from '@/lib/atlas/builder/public-output';
import { CARD, SECTION_HEADING } from '../../_ui';

export default async function ReviewStage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const draft = await (await createRequestStore()).getDraft(slug);
  if (!draft) notFound();

  const validation = validateAtlas(draft);

  // Only build a preview once the records are actually valid — publicAtlasSchema
  // would throw on an incomplete draft, and a stack trace is not a useful
  // review artifact. Until then the checklist above is the thing to read.
  let preview: Record<string, string> = {};
  let sitemapPaths: string[] = [];
  if (validation.ok) {
    const synthetic = releaseRecordSchema.parse({
      slug: draft.slug,
      version: draft.version,
      state: 'published',
      releasedAt: new Date().toISOString(),
      releasedBy: 'preview',
      releaseNote: 'Preview only. This release record is not persisted.',
      supersedes: null,
      supersededBy: null,
      atlas: publicAtlasSchema.parse(draft),
    });
    preview = buildAllPublicOutput(synthetic);
    sitemapPaths = buildSitemapEntries(synthetic).map((entry) => entry.path);
  }

  const checklist = [
    { label: 'At least one claim, concept, and source', pass: validation.counts.claims > 0 && validation.counts.concepts > 0 && validation.counts.sources > 0 },
    { label: 'Every claim has a supporting source that can carry it', pass: !validation.errors.some((f) => f.code === 'unsourced-claim' || f.code === 'weak-support') },
    { label: 'Every claim states a boundary', pass: draft.claims.every((claim) => claim.limitations.trim().length > 0) },
    { label: 'Every claim has a status and a stable id', pass: draft.claims.every((claim) => claim.status && claim.id) },
    { label: 'No duplicate slugs or identifiers', pass: !validation.errors.some((f) => f.code === 'duplicate-slug' || f.code === 'duplicate-id' || f.code === 'duplicate-source') },
    { label: 'No dangling source or concept references', pass: !validation.errors.some((f) => f.code === 'missing-source' || f.code === 'missing-concept') },
    { label: 'No dates in the future', pass: !validation.errors.some((f) => f.code === 'date-future') },
    { label: 'Slug is available and not reserved', pass: !validation.errors.some((f) => f.code === 'slug-reserved' || f.code === 'slug-taken') },
    { label: 'Atlas states its boundary and at least one exclusion', pass: draft.editorialBoundary.trim().length > 0 && draft.exclusions.length > 0 },
  ];

  return (
    <div className="grid gap-12">
      <section aria-labelledby="checklist">
        <h2 id="checklist" className={SECTION_HEADING}>
          Validation checklist
        </h2>
        <ul className="mt-6 grid gap-2 md:grid-cols-2">
          {checklist.map((item) => (
            <li key={item.label} className="flex items-start gap-3 text-sm leading-relaxed">
              <span className={item.pass ? 'text-cyan-400' : 'text-amber-400'}>
                {item.pass ? '✓' : '✗'}
              </span>
              <span className={item.pass ? 'text-zinc-400' : 'text-amber-200'}>{item.label}</span>
            </li>
          ))}
        </ul>

        {validation.warnings.length > 0 ? (
          <div className={`mt-8 ${CARD}`}>
            <p className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
              Advisory · {validation.warnings.length} · does not block release
            </p>
            <ul className="mt-3 space-y-1.5">
              {validation.warnings.map((finding, index) => (
                <li key={`${finding.code}-${index}`} className="text-xs leading-relaxed text-zinc-500">
                  <span className="font-mono">
                    {finding.target.kind}
                    {'id' in finding.target ? ` ${finding.target.id}` : ''}
                  </span>{' '}
                  — {finding.message}
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </section>

      <section aria-labelledby="public-preview">
        <h2 id="public-preview" className={SECTION_HEADING}>
          Public output preview
        </h2>
        <p className="mt-5 max-w-3xl text-sm leading-relaxed text-zinc-500">
          Generated by the same serializer that runs at release, from a draft parsed through the
          public schema. What you see here is byte-for-byte what would be served. Private notes and
          the change log are absent because the schema drops them, not because this view hides them.
        </p>

        {!validation.ok ? (
          <p className="mt-6 text-sm text-amber-300">
            Preview unavailable until the blocking issues above are resolved.
          </p>
        ) : (
          <>
            <div className="mt-6">
              <p className="font-mono text-[10px] uppercase tracking-widest text-zinc-600">
                URLs this release would create · {sitemapPaths.length}
              </p>
              <ul className="mt-3 grid gap-1">
                {sitemapPaths.map((path) => (
                  <li key={path} className="font-mono text-[11px] text-cyan-400">
                    {path}
                  </li>
                ))}
              </ul>
            </div>

            <div className="mt-8 grid gap-6">
              {Object.entries(preview).map(([routePath, body]) => (
                <details key={routePath} className="border border-zinc-800 bg-[#121214]">
                  <summary className="cursor-pointer px-5 py-3 font-mono text-[10px] uppercase tracking-widest text-cyan-300">
                    {routePath}
                    <span className="ml-3 text-zinc-600">{body.length} bytes</span>
                  </summary>
                  <pre className="max-h-96 overflow-auto border-t border-zinc-800 px-5 py-4 text-[11px] leading-relaxed text-zinc-400">
                    {body}
                  </pre>
                </details>
              ))}
            </div>
          </>
        )}
      </section>

      <section aria-labelledby="history">
        <h2 id="history" className={SECTION_HEADING}>
          Change log
        </h2>
        <p className="mt-5 text-xs leading-relaxed text-zinc-600">
          Who changed what, and when. Private — this is operator activity, not published record.
        </p>
        <ul className="mt-5 space-y-2">
          {formatChangeLog(draft, 40).map((entry) => (
            <li key={entry} className="font-mono text-[10px] leading-relaxed text-zinc-500">
              {entry}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
